name: reviewdog
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run ruff
        uses: chartboost/ruff-action@v1
        with:
          args: --fix -e
      - name: Suggest
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: ruff
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkt out repository code
        uses: actions/checkout@v4
      - name: Run black
        uses: reviewdog/action-black@v3
        with:
          reporter: github-pr-review